### PR TITLE
Upgrade to 2.2.6

### PR DESCRIPTION
**Pull request by FabienChaynes**
EmojiOne 2.2.6 [was released](https://github.com/Ranks/emojione/commit/b7735017f97aeea9e2fa9e35adbf25b81deda2ad) a few months ago.

This PR updates the different assets.

It also adds the `emojione-awesome.scss` file, allowing the use of [Emojione Awesome](https://github.com/Ranks/emojione/tree/master/lib/emojione-awesome) if it's requested in the CSS/SCSS manifest (it's optionnal though).

### CODE REVIEW

**Comment by nel** [comment]
Before putting it back into Dimelo, could you make sure that you test it against a big thread full of emoji. There is one on domain test with 1k+ emojis.

I had to fork the initial version of emojione.js with memoization to get decent performance, can't see in your diff regression though so maybe I merged it earlier, can't remember.

**Comment by nel** [comment]
Actually this seems to have been updated upsteam https://github.com/Ranks/emojione/issues/45

I pull requested the rest (svg ...) so we should be fine.

**Comment by FabienChaynes** [comment]
Good to know!

I'll double check tomorrow on the test thread to be sure.

**Comment by nel** [comment]
ok actually the patch is in DD code in app/assets/javascripts/emoji.js and can probably be removed

      // emojione monkey patch for perf improvement
      emojione._mapShortToUnicode = emojione.mapShortToUnicode;
      emojione.mapShortToUnicode = function() {
        if (!emojione.memMapShortToUnicode) {
          emojione.memMapShortToUnicode = emojione._mapShortToUnicode();
        }
        return emojione.memMapShortToUnicode;
      };

**Pull request merged**
